### ISSUE TITLE
 Float64Column.Values() panic when nNull > 0

### ISSUE THREAD

**Issue by longwallstreet** [sglyon/feather#1]
Hi, sglyon
      thank you for open source, i find a problem, when nNull > 0, Float64Colume.Values() panic in column.go.

**Comment by sglyon** [comment]
Hi @longwallstreet thanks for opening.

In order to help here I think I’d need to see the code you are trying to as as well as the data (if possible) so I can try it  out with you.

I do test a case where there are missing values in [this test case](https://github.com/sglyon/feather/blob/6bc4714b731770a94c8b96f2fed0cd059b48d969/feather_test.go#L222), so I know that it does work, at least in some cases (I’m not sure when it fails)...

**Comment by longwallstreet** [comment]
Hi @sglyon 
data: testnull.csv

```
symbol,lastpx
AAPL,181.9
AMZN,1600
JD,NaN
BABA,192.5
```

Step 1. use python translate testnull.csv to testnull.feather

```
import feather
import pandas as pd
df = pd.read_csv('/home/xujun/work/yi-build/testnull.csv')
feather.write_dataframe(df,'/home/xujun/work/yi-build/testnull.feather')
```

Step 2. use golang read testnull.feather

```
package main

import (
	"fmt"
	"math"

	"github.com/sglyon/feather"
)

func main() {
	src, err := feather.Read("/home/xujun/work/yi-build/testnull.feather")
	if err != nil {
		panic(err)
	}
	for i := 0; i < src.NumCols(); i++ {
		if src.Columns[i].Name() == "lastpx" {
			lastpxCol := src.Columns[i].(*feather.Float64Column)
			vals, _ := lastpxCol.Values()
			for _, val := range vals {
				if val == math.Inf(1) {
					fmt.Printf("Inf value\n")
				}
			}
		}
	}
}
```


lastpxCol.Values() panic.

**Comment by sglyon** [comment]
Great thank you! That's a very good example. I'll see what's going wrong within the next couple of days

**Comment by sglyon** [comment]
Thanks for posting. You exposed a bug in the library that is now fixed!

**Comment by longwallstreet** [comment]
thanks. @sglyon
